workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG  
    - if: '$CI_PIPELINE_SOURCE == "push"'

image: registry.gitlab.com/budiprihhastomo/flutter-docker:latest


stages: 
  - test
  - build 


cache: 
  key: $CI_COMMIT_REF_SLUG
  paths: 
    - .gradle/wrapper
    - .gradle/caches
    - .pub-cache/global_packages

before_script:
  - chmod +x ./android/gradlew
  - flutter doctor -v
  - echo flutter.sdk=${pwd}/flutter > android/local.properties
  - echo sdk.dir=${ANDROID_HOME} >> android/local.properties


build: 
  stage: build
  script:
    - echo "build an application"
    - flutter pub get
    - flutter build apk --split-per-abi
    - flutter build appbundle