workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG  
    - if: '$CI_PIPELINE_SOURCE == "push"'

image: registry.gitlab.com/mahmud120398/flutter-android-31


stages: 
  - test
  - build 
  - deploy-beta
  - deploy-prod


cache: 
  key: $CI_COMMIT_REF_SLUG
  paths: 
    - .gradle/wrapper
    - .gradle/caches
    - .pub-cache/global_packages

before_script:
  - flutter doctor -v
  - echo flutter.sdk=${FLUTTER_HOME} > android/local.properties
  - echo sdk.dir=${ANDROID_HOME} >> android/local.properties
  - echo ${FASTLANE_CREDENTIAL} -d | base64 > android/fastlane/publis-credential.json
  - echo ${KEY_JKS} | base64 -d > android/app/key.jks
  - echo ${KEY_PROPERTIES} | base64 -d > android/key.properties

test: 
  stage: test
  script:
    - echo "running test application"
    - flutter pub get 
    - flutter test

build: 
  stage: build
  script:
    - flutter pub get
    - flutter build apk --split-per-abi --release

  artifacts:
    paths:
      - build/app/outputs/apk/release/*.apk 

deploy:
  stage: deploy-beta
  rules:
    - if: $CI_COMMIT_TAG  
  script: 
    - echo "running flutter deploy to beta tester"
    - flutter pub get
    - flutter build appbundle --release 
    - cd android && fastlane android && fastlane beta

  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
      - android/fastlane/screenshots
      - android/fastlane/logs

deploy:
  stage: deploy-prod
  when: manual 
  script: 
    - echo "running flutter deploy"
    - flutter pub get
    - flutter build appbundle --release 
    - cd android && fastlane android && fastlane deploy

  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
      - android/fastlane/screenshots
      - android/fastlane/logs